# Generated by Django 5.0.6 on 2024-06-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_access_level'),
        ('stock', '0003_rename_reorder_poing_stockcontrol_reorder_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_controls', to='accounts.customer'),
        ),
    ]
