# Generated by Django 5.2 on 2025-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockcontrol_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='low_stock_warning_quantity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='preferred_quantity',
            field=models.BooleanField(default=True),
        ),
    ]
