# Generated by Django 5.2 on 2025-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockcontrol_low_stock_warning_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='low_stock_warning_quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
