# Generated by Django 5.2 on 2025-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stockcontrol_preferred_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
