

STOCK_INITIAL_DATA = [
    {"id": 1,  "warehouse": 1, "quantity": 60, "product": 1},
    {"id": 2,  "warehouse": 1, "quantity": 25, "product": 2},
    {"id": 3,  "warehouse": 1, "quantity": 30, "product": 3},
    {"id": 4,  "warehouse": 1, "quantity": 30, "product": 4},
    {"id": 5,  "warehouse": 1, "quantity": 55, "product": 5},
    {"id": 6,  "warehouse": 1, "quantity": 15, "product": 6},
    {"id": 7,  "warehouse": 1, "quantity": 18, "product": 7},
    {"id": 8,  "warehouse": 1, "quantity": 15, "product": 8},
    {"id": 9,  "warehouse": 1, "quantity": 12, "product": 9},
    {"id": 10, "warehouse": 1, "quantity": 15, "product": 10},
    {"id": 11, "warehouse": 1, "quantity": 13, "product": 11},
    {"id": 12, "warehouse": 1, "quantity": 15, "product": 12},
    {"id": 13, "warehouse": 1, "quantity": 15, "product": 13},
    {"id": 14, "warehouse": 1, "quantity": 15, "product": 14},
    {"id": 15, "warehouse": 1, "quantity": 12, "product": 15},
    {"id": 16, "warehouse": 1, "quantity": 20, "product": 16},
    {"id": 17, "warehouse": 1, "quantity": 12, "product": 17},
    {"id": 18, "warehouse": 1, "quantity": 12, "product": 18},
    {"id": 19, "warehouse": 1, "quantity": 12, "product": 19},
    {"id": 20, "warehouse": 1, "quantity": 15, "product": 20},
    {"id": 21, "warehouse": 1, "quantity": 22, "product": 21},
    {"id": 22, "warehouse": 1, "quantity": 45, "product": 22},
    {"id": 23, "warehouse": 1, "quantity": 50, "product": 23},
    {"id": 24, "warehouse": 1, "quantity": 15, "product": 24},
    {"id": 25, "warehouse": 1, "quantity": 11, "product": 25}
]
STOCK_CONTROL_INITIAL_DATA = [
    {"id": 1,  "preferred_quantity": 75, "reorder_point": 20,  "product": 1, "customer": 4},
    {"id": 2,  "preferred_quantity": 50, "reorder_point": 20,  "product": 2, "customer": 4},
    {"id": 3,  "preferred_quantity": 50, "reorder_point": 15,  "product": 3, "customer": 4},
    {"id": 4,  "preferred_quantity": 50, "reorder_point": 15,  "product": 4, "customer": 4},
    {"id": 5,  "preferred_quantity": 50, "reorder_point": 30,  "product": 5, "customer": 4},
    {"id": 6,  "preferred_quantity": 15, "reorder_point": 15,  "product": 6, "customer": 5},
    {"id": 7,  "preferred_quantity": 15, "reorder_point": 10,  "product": 7, "customer": 5},
    {"id": 8,  "preferred_quantity": 15, "reorder_point": 10,  "product": 8, "customer": 5},
    {"id": 9,  "preferred_quantity": 15, "reorder_point": 10,  "product": 9, "customer": 5},
    {"id": 10, "preferred_quantity": 15, "reorder_point": 10, "product": 10, "customer": 5},
    {"id": 11, "preferred_quantity": 15, "reorder_point": 10, "product": 11, "customer": 6},
    {"id": 12, "preferred_quantity": 15, "reorder_point": 10, "product": 12, "customer": 6},
    {"id": 13, "preferred_quantity": 15, "reorder_point": 10, "product": 13, "customer": 6},
    {"id": 14, "preferred_quantity": 15, "reorder_point": 10, "product": 14, "customer": 6},
    {"id": 15, "preferred_quantity": 15, "reorder_point": 10, "product": 15, "customer": 6},
    {"id": 16, "preferred_quantity": 25, "reorder_point": 20, "product": 16, "customer": 7},
    {"id": 17, "preferred_quantity": 15, "reorder_point": 10, "product": 17, "customer": 7},
    {"id": 18, "preferred_quantity": 15, "reorder_point": 10, "product": 18, "customer": 7},
    {"id": 19, "preferred_quantity": 15, "reorder_point": 10, "product": 19, "customer": 7},
    {"id": 20, "preferred_quantity": 15, "reorder_point": 10, "product": 20, "customer": 7},
    {"id": 21, "preferred_quantity": 15, "reorder_point": 10, "product": 21, "customer": 8},
    {"id": 22, "preferred_quantity": 35, "reorder_point": 30, "product": 22, "customer": 8},
    {"id": 23, "preferred_quantity": 35, "reorder_point": 30, "product": 23, "customer": 8},
    {"id": 24, "preferred_quantity": 15, "reorder_point": 10, "product": 24, "customer": 8},
    {"id": 25, "preferred_quantity": 15, "reorder_point": 10, "product": 25, "customer": 8},
]