# Generated by Django 5.0.6 on 2024-06-29 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPrinterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('printer_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pos_printer_selections', to='pos.cashregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pos_printer_selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='posprinterselection',
            constraint=models.UniqueConstraint(fields=('key', 'cash_register'), name='unique_printer_keys'),
        ),
    ]
