# Generated by Django 5.0.6 on 2024-06-29 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
        ('products', '0009_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PosPrinterSelectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_width', models.SmallIntegerField(default=32)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('feed_lines', models.SmallIntegerField(default=0)),
                ('cut_paper', models.BooleanField(default=0)),
                ('print_bitmap', models.SmallIntegerField(default=0)),
                ('open_cash_drawer', models.BooleanField(default=1)),
                ('cash_drawer_command', models.CharField(max_length=100)),
                ('header_alignment', models.SmallIntegerField(default=0)),
                ('footer_alignment', models.SmallIntegerField(default=0)),
                ('is_formatting_enabled', models.BooleanField(default=False)),
                ('printer_type', models.SmallIntegerField(default=0)),
                ('number_of_copies', models.SmallIntegerField(default=1)),
                ('code_page', models.SmallIntegerField(default=-1)),
                ('character_set', models.SmallIntegerField(default=-1)),
                ('margin', models.SmallIntegerField(default=0)),
                ('left_margin', models.FloatField(default=1)),
                ('top_margin', models.FloatField(default=0)),
                ('right_margin', models.FloatField(default=0)),
                ('bottom_margin', models.FloatField(default=0)),
                ('print_barcode', models.SmallIntegerField(default=1)),
                ('font_name', models.CharField(max_length=100)),
                ('font_size_percent', models.FloatField(default=100.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pos_printer_selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_selection_settings', to='printers.posprinterselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_selection_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PosPrinterSelectionSettings',
            },
        ),
        migrations.CreateModel(
            name='PosPrinterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=100, unique=True)),
                ('paper_width', models.SmallIntegerField(default=32)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('feed_lines', models.SmallIntegerField(default=0)),
                ('cut_paper', models.SmallIntegerField(default=1)),
                ('print_bitmap', models.SmallIntegerField(default=0)),
                ('open_cash_drawer', models.SmallIntegerField(default=1)),
                ('cash_drawer_command', models.CharField(max_length=100)),
                ('header_alignment', models.SmallIntegerField(default=0)),
                ('footer_alignment', models.SmallIntegerField(default=0)),
                ('is_formatting_enabled', models.BooleanField(default=False)),
                ('printer_type', models.SmallIntegerField(default=0)),
                ('number_of_copies', models.SmallIntegerField(default=1)),
                ('code_page', models.SmallIntegerField(default=-1)),
                ('character_set', models.SmallIntegerField(default=-1)),
                ('margin', models.SmallIntegerField(default=0)),
                ('left_margin', models.FloatField(default=1)),
                ('top_margin', models.FloatField(default=0)),
                ('right_margin', models.FloatField(default=0)),
                ('bottom_margin', models.FloatField(default=0)),
                ('print_barcode', models.SmallIntegerField(default=1)),
                ('font_name', models.CharField(max_length=100)),
                ('font_size_percent', models.FloatField(default=100.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PosPrinterSettings',
            },
        ),
        migrations.CreateModel(
            name='PrintStationPosPrinterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_printer_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.posprinterselection')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printstation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupPrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_group_print_stations', to='printers.printstation')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_group_print_stations', to='products.productgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_group_print_stations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrintStations', to='printers.printstation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrintStations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrintStations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='posprintersettings',
            constraint=models.UniqueConstraint(fields=('id', 'printer_name'), name='unique_printer_name'),
        ),
        migrations.AddConstraint(
            model_name='printstationposprinterselection',
            constraint=models.UniqueConstraint(fields=('print_station', 'pos_printer_selection'), name='unique_printer_pos_printer_selection'),
        ),
        migrations.AddConstraint(
            model_name='productgroupprintstation',
            constraint=models.UniqueConstraint(fields=('product_group', 'print_station'), name='pg_print_station'),
        ),
        migrations.AddConstraint(
            model_name='productprintstation',
            constraint=models.UniqueConstraint(fields=('product', 'print_station'), name='product_print_station'),
        ),
    ]
