# Generated by Django 5.0.6 on 2024-06-29 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_printstation_created_printstation_updated'),
        ('products', '0009_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprintstation',
            name='print_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_print_stations', to='printers.printstation'),
        ),
        migrations.AlterField(
            model_name='productprintstation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_print_stations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productprintstation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_print_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
