# Generated by Django 5.0.6 on 2024-07-13 17:55

import django.db.models.deletion
import src.core.modules
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_alter_productprintstation_print_station_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLetterheadOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company Letterhead Options', max_length=30)),
                ('unicode_font', models.FileField(blank=True, null=True, upload_to=src.core.modules.upload_file_path)),
                ('unicode_text_header_size', models.PositiveSmallIntegerField(default=24)),
                ('text_header_size', models.PositiveSmallIntegerField(default=17)),
                ('unicode_text_content_size', models.PositiveSmallIntegerField(default=12)),
                ('text_content_size', models.PositiveSmallIntegerField(default=9)),
                ('table_text_content_size', models.PositiveSmallIntegerField(default=9)),
                ('font_family', models.CharField(default='helvetica', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_letterhead_options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLetterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company Letterhead', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterheads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_letterheads', to=settings.AUTH_USER_MODEL)),
                ('letterhead_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='printers.companyletterheadoption')),
            ],
        ),
    ]
