# Generated by Django 5.0.6 on 2024-07-13 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_companyletterhead_created_companyletterhead_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyletterheadoption',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyletterheadoption',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
