# Generated by Django 5.0.6 on 2024-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0007_companyletterheadoption_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyletterhead',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
