# Generated by Django 5.0.6 on 2024-07-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_region'),
        ('printers', '0008_companyletterhead_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyletterhead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterheads', to='accounts.company'),
        ),
    ]
