# Generated by Django 5.0.6 on 2024-07-14 10:11

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0010_companyletterheadoption_bottom_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyletterheadoption',
            name='inner_height',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('paper_height'), '-', models.F('left_margin')), '-', models.F('left_margin')), output_field=models.PositiveSmallIntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='companyletterheadoption',
            name='inner_width',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('paper_width'), '-', models.F('left_margin')), '-', models.F('left_margin')), output_field=models.PositiveSmallIntegerField(default=0)),
        ),
    ]
