# Generated by Django 5.2 on 2025-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_cashregister_name_alter_cashregister_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='name',
            field=models.CharField(default='DARYA-HOME-DELL', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='number',
            field=models.CharField(db_index=True, default='509a4c12a32c', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
