# Generated by Django 5.2 on 2025-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_alter_cashregister_name_alter_cashregister_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='name',
            field=models.CharField(default='DESKTOP-0JB92VA', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='number',
            field=models.CharField(db_index=True, default='207918be0e50', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
