# Generated by Django 5.2 on 2025-08-16 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customer_slug'),
        ('pos', '0018_alter_cashregister_name_alter_cashregister_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_registers', to='accounts.warehouse'),
        ),
    ]
