payment_types_initial_data = [
    {
        "id": 1,
        "user_id": 1,
        "name": "Cash",
        "code": "",
        "is_customer_required": False,
        "is_fiscal": True,
        "is_slip_required": False,
        "is_change_allowed": True,
        "ordinal": 1,
        "is_enabled": True,
        "is_quick_payment": True,
        "open_cash_drawer": True,
        "shortcut": "",
        "mark_as_paid": True,
    },
    {
        "id": 2,
        "user_id": 1,
        "name": "Credit Card",
        "code": "",
        "is_customer_required": False,
        "is_fiscal": True,
        "is_slip_required": False,
        "is_change_allowed": False,
        "ordinal": 2,
        "is_enabled": True,
        "is_quick_payment": True,
        "open_cash_drawer": True,
        "shortcut": "",
        "mark_as_paid": True,
    },
    {
        "id": 3,
        "user_id": 1,
        "name": "Debit Card",
        "code": "",
        "is_customer_required": False,
        "is_fiscal": True,
        "is_slip_required": False,
        "is_change_allowed": False,
        "ordinal": 3,
        "is_enabled": True,
        "is_quick_payment": True,
        "open_cash_drawer": True,
        "shortcut": "",
        "mark_as_paid": True,
    },
    {
        "id": 4,
        "user_id": 1,
        "name": "Check",
        "code": "",
        "is_customer_required": False,
        "is_fiscal": True,
        "is_slip_required": False,
        "is_change_allowed": False,
        "ordinal": 4,
        "is_enabled": True,
        "is_quick_payment": True,
        "open_cash_drawer": True,
        "shortcut": "",
        "mark_as_paid": True,
    },
    {
        "id": 5,
        "user_id": 1,
        "name": "Voucher",
        "code": "",
        "is_customer_required": False,
        "is_fiscal": True,
        "is_slip_required": False,
        "is_change_allowed": False,
        "ordinal": 5,
        "is_enabled": True,
        "is_quick_payment": True,
        "open_cash_drawer": True,
        "shortcut": "",
        "mark_as_paid": True,
    },
    {
        "id": 6,
        "user_id": 1,
        "name": "Gift Card",
        "code": "",
        "is_customer_required": False,
        "is_fiscal": True,
        "is_slip_required": False,
        "is_change_allowed": False,
        "ordinal": 6,
        "is_enabled": True,
        "is_quick_payment": True,
        "open_cash_drawer": True,
        "shortcut": "",
        "mark_as_paid": True,
    },
]
