# Generated by Django 5.0.6 on 2024-05-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(blank=True, default='pcs', max_length=10, null=True),
        ),
    ]
