# Generated by Django 5.0.6 on 2024-06-29 12:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_group',
            field=mptt.fields.TreeForeignKey(default='products', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productgroup'),
        ),
    ]
