# Generated by Django 5.0.6 on 2024-07-10 17:29

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug2',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
