# Generated by Django 5.0.6 on 2024-07-10 17:33

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_slug2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='pod', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug2',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
