# Generated by Django 5.0.6 on 2024-07-10 17:49

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='w', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
