# Generated by Django 5.0.6 on 2024-07-10 19:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_color2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color2',
            field=models.CharField(default='Transparent', max_length=50),
        ),
    ]
