# Generated by Django 5.0.6 on 2024-07-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_color_alter_product_color2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug2',
        ),
    ]
