# Generated by Django 5.0.6 on 2024-07-16 09:55

import src.core.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_slug2'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='image',
            field=models.ImageField(blank=True, upload_to=src.core.modules.upload_barcode_path),
        ),
    ]
