# Generated by Django 5.0.6 on 2024-07-16 15:40

import colorfield.fields
import src.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='value',
            field=models.CharField(default=src.core.utils.generate_ean13, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
