# Generated by Django 5.0.6 on 2024-07-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_barcode_value_alter_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'ordering': ('product__parent_group__id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('parent_group__id',)},
        ),
    ]
