# Generated by Django 5.0.6 on 2024-08-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_barcode_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color2',
        ),
    ]
