# Generated by Django 5.0.6 on 2025-01-03 08:42

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
