# Generated by Django 5.0.6 on 2025-01-03 08:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=django_countries.fields.CountryField(default='cn', max_length=2),
            preserve_default=False,
        ),
    ]
