# Generated by Django 5.0.6 on 2025-01-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin',
        ),
    ]
