# Generated by Django 5.2 on 2025-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
