# Generated by Django 5.0.6 on 2024-05-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationproperty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Migration',
        ),
        migrations.DeleteModel(
            name='ApplicationProperty',
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
