# Generated by Django 5.0.6 on 2024-06-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.SmallIntegerField(default=1)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(choices=[('', 'Select InputType'), ('text', 'text'), ('textarea', 'textarea'), ('file', 'file'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('button', 'button'), ('select', 'select')], default='', max_length=255)),
                ('editable', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('params', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPropertySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.applicationpropertysection')),
            ],
        ),
    ]
