# Generated by Django 5.0.6 on 2024-05-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationProperty',
        ),
    ]
