# Generated by Django 5.0.6 on 2024-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
