# Generated by Django 5.0.6 on 2024-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_delete_applicationproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.SmallIntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
