# Generated by Django 5.0.6 on 2024-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_applicationproperty_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationproperty',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
