# Generated by Django 5.0.6 on 2024-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_applicationproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationproperty',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
