# Generated by Django 5.0.6 on 2024-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_alter_applicationproperty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='input_type',
            field=models.CharField(choices=[('', 'Select InputType'), ('text', 'text'), ('textarea', 'textarea'), ('file', 'file'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('button', 'button'), ('select', 'select')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
