# Generated by Django 5.0.6 on 2024-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_applicationpropertysection_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationproperty',
            name='input_type',
            field=models.CharField(choices=[('', 'Select InputType'), ('text', 'text'), ('number', 'number'), ('textarea', 'textarea'), ('file', 'file'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('button', 'button'), ('select', 'select')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationproperty',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
