# Generated by Django 5.0.6 on 2024-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_alter_applicationproperty_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpropertysection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
