# Generated by Django 5.0.6 on 2024-06-04 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_applicationpropertysection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpropertysection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationpropertysection',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
