# Generated by Django 5.0.6 on 2024-06-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_securitykey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityKey',
        ),
    ]
