# Generated by Django 5.0.6 on 2024-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_apptablecolumn_is_enabled_apptablecolumn_is_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptablecolumn',
            name='related_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
