# Generated by Django 5.2 on 2025-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0014_apptablecolumn_orderable_apptablecolumn_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
