# Generated by Django 5.0.6 on 2024-05-25 06:39

import src.core.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_logo_company_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=src.core.modules.upload_image_file_path),
        ),
    ]
