# Generated by Django 5.0.6 on 2024-06-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_securitykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_level', to='accounts.securitykey'),
        ),
    ]
