# Generated by Django 5.0.6 on 2024-07-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
