# Generated by Django 5.0.6 on 2024-12-14 18:35

import src.core.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=src.core.modules.upload_image_file_path),
        ),
    ]
