# Generated by Django 5.2 on 2025-08-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(default='27bf9a07-2fb3-4f3d-8b68-fab6dd44d67e', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.store'),
            preserve_default=False,
        ),
    ]
