

INITIAL_DATA = [
    {"id": 1, "name": "Theme.mode", "value": 'dark', "title": '', "description": ''},
    {"id": 2, "name": "Theme.color", "value": 'pink', "title": '', "description": ''},
    {"id": 3, "name": "Theme.cover", "value": '1', "title": '', "description": ''},
    {"id": 4, "name": "Site.title", "value": 'Zeneon LLC.',
        "title": 'Site title', "description": ''},
    {"id": 5, "name": "Site.language", "value": 'en-us',
        "title": 'Language', "description": ''},
    {"id": 6, "name": "Site.writing_direction",
        "value": 'left_to_right', "title": 'Writing Direction', "description": ''},
    {"id": 7, "name": "Site.cover", "value": '1',
        "title": 'Site Background Image', "description": ''},
    {"id": 8, "name": "POS.application.layout",
        "value": 'visual', "title": 'Layout', "description": ''},
    {"id": 9, "name": "POS.application.num_of_rows",
        "value": '4', "title": 'Number of Rows', "description": ''},
    {"id": 10, "name": "POS.application.num_of_columns",
        "value": '4', "title": 'Number of Columns', "description": ''},
    {"id": 11, "name": "POS.application.virtual_keyboard",
        "value": 'False', "title": 'Enable Virtual Keyboard', "description": ''},
    {"id": 12, "name": "POS.application.zoom",
        "value": '100%', "title": 'Zoom', "description": ''},
    {"id": 13, "name": "POS.messages.close_button",
        "value": 'True', "title": 'Show "Close" Button', "description": ''},
    {"id": 14, "name": "POS.messages.duration",
        "value": '5', "title": 'Duration', "description": ''},
    {"id": 15, "name": "POS.messages.position",
        "value": 'top', "title": 'Position', "description": ''},
    {"id": 16, "name": "POS.button_bar.note",
        "value": 'top', "title": '', "description": '* Applicable for visual layout only!'},

    {"id": 17, "name": "POS.button_bar.search",
        "value": 'True', "title": '', "description": ''},
    {"id": 18, "name": "POS.button_bar.discount",
        "value": 'True', "title": '', "description": ''},
    {"id": 19, "name": "POS.button_bar.transfer",
        "value": 'True', "title": '', "description": ''},
    {"id": 20, "name": "POS.button_bar.comment",
        "value": 'False', "title": '', "description": ''},
    {"id": 21, "name": "POS.button_bar.new_sale",
        "value": 'True', "title": '', "description": ''},
    {"id": 22, "name": "POS.button_bar.refund",
        "value": 'True', "title": '', "description": ''},
    {"id": 23, "name": "POS.button_bar.refund",
        "value": 'True', "title": '', "description": ''},
    {"id": 24, "name": "POS.button_bar.order_name",
        "value": 'True', "title": '', "description": ''},
    {"id": 25, "name": "POS.button_bar.cash_drawer",
        "value": 'True', "title": '', "description": ''},
    {"id": 26, "name": "POS.button_bar.cash_drawer",
        "value": 'True', "title": '', "description": ''},
    # ORDER AND PAYMENT
    {"id": 26, "name": "POS.button_bar.cash_drawer",
        "value": 'True', "title": '', "description": ''},
]
