# Generated by Django 5.0.6 on 2024-05-27 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_country'),
        ('orders', '0001_initial'),
        ('pos', '0001_initial'),
        ('products', '0006_alter_product_measurement_unit'),
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_document_number', models.CharField(max_length=100, unique=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.SmallIntegerField(default=0)),
                ('discount_type', models.SmallIntegerField(default=0)),
                ('discount_apply_rule', models.SmallIntegerField(default=0)),
                ('paid_status', models.BooleanField(default=False)),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('is_clocked_out', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='pos.cashregister')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='accounts.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='orders.posorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='accounts.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('expected_quantity', models.SmallIntegerField(default=1)),
                ('price_before_tax', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('discount_type', models.FloatField(default=0)),
                ('product_cost', models.FloatField(default=0)),
                ('price_before_tax_after_discount', models.FloatField(default=0)),
                ('price_after_descount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('total_after_document_discount', models.FloatField(default=0)),
                ('discount_apply_rule', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to='documents.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_items', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_item_taxes', to='documents.documentitem')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_item_taxes', to='tax.tax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_item_taxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('stock_direction', models.SmallIntegerField(default=0)),
                ('editor_type', models.SmallIntegerField(default=0)),
                ('print_template', models.TextField(blank=True, null=True)),
                ('price_type', models.SmallIntegerField(default=0)),
                ('language', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='documents.documentcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='accounts.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='documents.documenttype'),
        ),
    ]
