# Generated by Django 5.0.6 on 2024-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
