# Generated by Django 5.0.6 on 2024-07-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentitem_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='paid_status',
            field=models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=False),
        ),
    ]
