# Generated by Django 5.0.6 on 2024-08-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_paid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentitem',
            old_name='price_after_descount',
            new_name='price_after_discount',
        ),
    ]
