# Generated by Django 5.0.6 on 2024-10-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_price_after_descount_documentitem_price_after_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
    ]
