# Generated by Django 5.0.6 on 2024-10-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_order'),
        ('orders', '0004_posorderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document', to='orders.posorder'),
        ),
    ]
