# Generated by Django 5.0.6 on 2024-11-24 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_date_alter_document_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 11, 54, 56, 841293)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 11, 54, 56, 841293)),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
