# Generated by Django 5.0.6 on 2024-12-05 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_date_alter_document_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitem',
            name='price_after_discount',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='price_before_tax',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='price_before_tax_after_discount',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='product_cost',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='total_after_document_discount',
        ),
        migrations.AddField(
            model_name='documentitem',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 10, 43, 42, 373677)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 10, 43, 42, 373677)),
        ),
    ]
