# Generated by Django 5.0.6 on 2024-12-05 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_remove_documentitem_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 23, 8, 6, 91130)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 23, 8, 6, 91130)),
        ),
    ]
