# Generated by Django 5.0.6 on 2024-12-06 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_date_alter_document_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documentitemtax',
            name='document_item',
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 14, 56, 13, 122617)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 14, 56, 13, 122617)),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='number',
            field=models.CharField(db_index=True, default='item-', max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
