# Generated by Django 5.0.6 on 2024-12-07 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_remove_documentitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 11, 24, 45, 265126)),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 11, 24, 45, 265126)),
        ),
    ]
