# Generated by Django 5.2 on 2025-06-03 15:38

import src.documents.models.model_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0069_alter_document_date_alter_document_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.SmallIntegerField(default=src.documents.models.model_document.get_due_date),
        ),
    ]
