# Generated by Django 5.2 on 2025-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0070_alter_document_date_alter_document_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.SmallIntegerField(default=15),
        ),
    ]
