# Generated by Django 5.0.6 on 2024-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_posorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='id',
        ),
        migrations.AddField(
            model_name='posorder',
            name='number',
            field=models.CharField(db_index=True, default='order-01-00000', max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
