# Generated by Django 5.0.6 on 2024-10-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_posorder_id_posorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.posorder'),
        ),
    ]
