# Generated by Django 5.0.6 on 2024-11-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_date_alter_document_due_date'),
        ('orders', '0005_rename_status_posorder_paid_status_posorder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='documents.documenttype'),
        ),
    ]
