# Generated by Django 5.0.6 on 2024-12-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_posorder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
