# Generated by Django 5.2 on 2025-04-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customer_image'),
        ('orders', '0008_posorder_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='warehouse',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounts.warehouse'),
        ),
    ]
