# Generated by Django 5.2 on 2025-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_posorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unfulfilled'), (2, 'Ready for pickup'), (3, 'Ready for delivery'), (4, 'Cancelled'), (5, 'Fulfilled')], default=1, help_text='Current status of the order'),
        ),
    ]
