# Generated by Django 5.2 on 2025-05-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_posorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
