# Generated by Django 5.2 on 2025-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_posorderitem_discount_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='discount_sign',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(discount_type=0, then=models.Value('%')), models.When(discount_type=1, then=models.Value('$')), default=models.Value(''), output_field=models.CharField(max_length=20)), output_field=models.CharField(max_length=20)),
        ),
    ]
