# Generated by Django 5.2 on 2025-05-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_posorderitem_discount_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='discounted_amount',
        ),
    ]
