# Generated by Django 5.2 on 2025-05-03 09:40

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_posorderitem_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='item_total',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(discount_type=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), '-', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), '*', django.db.models.expressions.CombinedExpression(models.F('discount'), '/', models.Value(100))))), models.When(discount_type=1, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), '-', models.F('discount'))), default=models.Value(0), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
