# Generated by Django 5.2 on 2025-05-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_posorderitem_item_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='discount_sign',
        ),
    ]
