# Generated by Django 5.2 on 2025-05-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_posorder_total_remove_posorder_total_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='subtotal_after_discount',
        ),
    ]
