# Generated by Django 5.2 on 2025-05-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_posorder_subtotal_after_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='discount_sign',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='discounted_amount',
        ),
    ]
