# Generated by Django 5.2 on 2025-05-04 07:09

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_posorder_discount_sign_posorder_discounted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='subtotal_after_discount',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('item_subtotal'), '-', models.F('discounted_amount')), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
