# Generated by Django 5.2 on 2025-05-04 07:10

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_posorder_subtotal_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='total_tax',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('fixed_taxes'), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_after_discount'), '*', models.F('total_tax_rate')), '/', models.Value(100))), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
        migrations.AddField(
            model_name='posorder',
            name='total',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('subtotal_after_discount'), '+', models.F('total_tax')), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
