# Generated by Django 5.2 on 2025-05-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_posorderitem_item_total_before_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='item_total_before_discount',
        ),
    ]
