# Generated by Django 5.2 on 2025-05-04 07:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_posorderitem_item_total_before_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='item_total_before_discount',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
