# Generated by Django 5.2 on 2025-05-05 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_posorderitem_item_total_before_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('ordinal', models.SmallIntegerField(unique=True)),
                ('color_class', models.CharField(choices=[('warning', 'border-warning text-warning'), ('info', 'border-info text-info'), ('primary', 'border-primary text-primary'), ('danger', 'border-danger text-danger'), ('success', 'border-success text-success'), ('default', 'border-default text-default')], default='default', max_length=55)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
    ]
