# Generated by Django 5.2 on 2025-05-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_posorderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.ForeignKey(default=1, help_text='Current status of the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.posorderstatus'),
        ),
    ]
