# Generated by Django 5.2 on 2025-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_posorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderstatus',
            name='color_class',
            field=models.CharField(choices=[('warning', 'border-warning text-warning'), ('info', 'border-info text-info'), ('primary', 'border-primary text-primary'), ('danger', 'border-danger text-danger'), ('success', 'border-success text-success'), ('default', 'btn-outline-default text-default')], default='default', max_length=55),
        ),
    ]
