# Generated by Django 5.2 on 2025-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_posorderstatus_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderstatus',
            name='color_class',
            field=models.CharField(choices=[('warning', 'warning'), ('info', 'info'), ('primary', 'primary'), ('danger', 'danger'), ('success', 'success'), ('default', 'default')], default='default', max_length=55),
        ),
    ]
