# Generated by Django 5.2 on 2025-08-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_posorderstatus_color_class'),
        ('pos', '0017_alter_cashregister_name_alter_cashregister_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.cashregister'),
        ),
    ]
