# Generated by Django 5.2 on 2025-08-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_posorder_cash_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posorder',
            options={'ordering': ['-created', 'is_enabled']},
        ),
    ]
