

DEFAULT_FONT_FAMILY = 'helvetica'
DEFAULT_UNICODE_HEADER_TEXT_SIZE = 24
DEFAULT_HEADER_TEXT_SIZE = 17
DEFAULT_CONTENT_TEXT_SIZE = 9
DEFAULT_UNICODE_CONTENT_TEXT_SIZE = 12
DEFAULT_TABLE_TEXT_SIZE = 9
