# Generated by Django 5.0.6 on 2024-07-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_assetclass_fund_indexvalue_fundvalue_theme_rationale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='finances.fund'),
        ),
    ]
